name: tagpr
on:
  push:
    branches:
      - main

jobs:
  tagpr:
    runs-on: ubuntu-latest
    outputs:
      tagpr-tag: ${{ steps.tagpr.outputs.tag }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - id: tagpr
        name: Run tagpr
        uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger release Workflow
        uses: actions/github-script@v6
        continue-on-error: true
        if: steps.tagpr.outputs.tag != ''
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let refs = '${{ fromJson(steps.tagpr.outputs.pull_request).head.ref }}'

            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release.yml',
              ref: refs,
              inputs: {
                tag: '${{ steps.tagpr.outputs.tag }}'
              },
            })