name: Test build
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test-job:
    name: Test job.
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: make dist/index.html